[package]
name = "ironsaga-macros"
version = "0.2.0"
edition = "2024"
authors = ["ALAWIII"]
description = "Proc-macro crate for ironsaga — not intended for direct use."
license = "MIT"
repository = "https://github.com/ALAWIII/ironsaga"

[dependencies]
heck = "0.5.0"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["extra-traits", "full"] }


[lib]
proc-macro = true
